name: release docker image

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:

      - name: Set tag name output
        id: tagname
        run: |
          if [[ -n "${{ github.event.inputs.git_tag }}" ]]; then
            TAG_NAME="${{ github.event.inputs.git_tag }}"
          else
            TAG_NAME=$(echo ${{ github.ref }} | sed 's/refs\/tags\///')
          fi
          echo "::set-output name=tagname::$TAG_NAME"
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.tagname.outputs.tagname }}
      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: alileza
          password: ${{ secrets.PAT }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/alileza/tf-summarize:${{ steps.tagname.outputs.tagname }}